'use client';
import { useState, useRef, useMemo } from 'react';
import Link from 'next/link';
import { marked } from 'marked';
import { saveFileAs } from '@/tools-logic/saveFile';

/* ==========================================================================
   PDF Summarize — Production Llama-only Version
   ========================================================================== */

const extractPageText = (textContent) => {
  const items = textContent.items;
  if (!items?.length) return '';
  let out = '';
  let lastY = null;
  let lastEndX = null;
  let lastFontHeight = 10;

  for (const it of items) {
    const tx = it.transform;
    if (!tx) {
      out += it.str + ' ';
      continue;
    }
    const x = tx[4];
    const y = tx[5];
    const fontHeight = Math.abs(tx[3]) || lastFontHeight;
    const w = it.width || 0;

    if (lastY !== null) {
      const lineGap = Math.abs(y - lastY);
      if (lineGap > fontHeight * 0.6) {
        out += '\n';
        if (lineGap > fontHeight * 1.5) out += '\n';
      } else if (lastEndX !== null && x - lastEndX > fontHeight * 0.3) {
        if (!out.endsWith(' ') && !out.endsWith('\n')) out += ' ';
      }
    }
    out += it.str;
    lastY = y;
    lastEndX = x + w;
    lastFontHeight = fontHeight;
  }
  return out.trim();
};

const chunkText = (text, maxLength = 45000) => {
  const chunks = [];
  let current = '';
  const paragraphs = text.split('\n');
  for (const para of paragraphs) {
    if ((current + '\n' + para).length > maxLength) {
      if (current) chunks.push(current.trim());
      current = para;
    } else {
      current += (current ? '\n' : '') + para;
    }
  }
  if (current) chunks.push(current.trim());
  return chunks.length ? chunks : [text];
};

const downloadBlob = async (text, filename, type) => {
  const blob = new Blob([text], { type });
  const ext = filename.match(/\.([^.]+)$/)?.[1] || 'txt';
  await saveFileAs(blob, filename, {
    description: ext.toUpperCase() + ' File',
    mimeType: type,
    extensions: ['.' + ext],
  });
};

const downloadPdf = async (text, filename) => {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(33, 37, 41);

  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxLineWidth = pageWidth - (margin * 2);
  const bottomMargin = 20;

  const sourceLines = text.split('\n');
  let y = margin;

  // Header Title
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('DOCUMENT SUMMARY', margin, y);
  y += 10;
  
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by Llama AI on ${new Date().toLocaleDateString()}`, margin, y);
  y += 10;

  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(33, 37, 41);

  for (const rawLine of sourceLines) {
    if (!rawLine.trim()) {
      y += 6;
      continue;
    }

    const wrappedLines = doc.splitTextToSize(rawLine, maxLineWidth);
    for (const line of wrappedLines) {
      if (y + 8 > pageHeight - bottomMargin) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += 6;
    }
  }

  const pdfBlob = doc.output('blob');
  await saveFileAs(pdfBlob, filename, {
    description: 'PDF Document',
    mimeType: 'application/pdf',
    extensions: ['.pdf'],
  });
};

export default function SummarizePdf() {
  const [file, setFile] = useState(null);
  const [summary, setSummary] = useState('');
  const [phase, setPhase] = useState('idle'); // 'idle' | 'extracting' | 'summarizing' | 'done' | 'error'
  const [extractProgress, setExtractProgress] = useState({ current: 0, total: 0 });
  const [summarizeProgress, setSummarizeProgress] = useState({ current: 0, total: 0, combining: false });
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);
  const fileInputRef = useRef(null);

  const summaryHtml = useMemo(() => {
    if (!summary) return '';
    try {
      marked.setOptions({ breaks: true, gfm: true });
      return marked.parse(summary);
    } catch {
      return summary.replace(/\n/g, '<br/>');
    }
  }, [summary]);

  const handleFileChange = async (e) => {
    const f = e.target.files?.[0];
    if (!f) return;
    if (f.type !== 'application/pdf') {
      setError('Please select a valid PDF file.');
      return;
    }
    setFile(f);
    setSummary('');
    setError(null);
    setPhase('extracting');

    try {
      // 1. Extract Text
      const pdfjsLib = await import('pdfjs-dist/legacy/build/pdf.js');
      pdfjsLib.GlobalWorkerOptions.workerSrc =
        `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;

      const arrayBuffer = await f.arrayBuffer();
      const pdf = await pdfjsLib.getDocument({ data: new Uint8Array(arrayBuffer) }).promise;
      const n = pdf.numPages;
      setExtractProgress({ current: 0, total: n });

      const parts = new Array(n);
      for (let i = 1; i <= n; i++) {
        const page = await pdf.getPage(i);
        const tc = await page.getTextContent();
        parts[i - 1] = extractPageText(tc);
        setExtractProgress({ current: i, total: n });
      }
      try { pdf.destroy?.(); } catch {}

      const text = parts.map((t, idx) => `\n--- PAGE ${idx + 1} ---\n${t}`).join('\n').trim();
      const cleanText = text.replace(/--- PAGE \d+ ---/g, '').trim();

      if (!cleanText) {
        setPhase('error');
        setError('No selectable text found in this PDF. It looks like a scanned document.');
        return;
      }

      // 2. Summarize (Llama API via /api/chat)
      setPhase('summarizing');
      const chunks = chunkText(cleanText, 45000);
      setSummarizeProgress({ current: 0, total: chunks.length, combining: false });

      let finalSummary = '';

      if (chunks.length === 1) {
        setSummarizeProgress({ current: 1, total: 1, combining: false });
        const response = await fetch('/api/chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            messages: [
              {
                role: 'user',
                content: `Please provide a clear, comprehensive summary of the following document. Use bullet points and clear sections with headings where appropriate:\n\n${chunks[0]}`
              }
            ],
            selectedModel: 'meta-llama/llama-4-scout-17b-16e-instruct'
          })
        });

        const data = await response.json();
        if (!response.ok) throw new Error(data.error || 'Failed to summarize.');
        finalSummary = data.message;
      } else {
        const chunkSummaries = [];
        for (let i = 0; i < chunks.length; i++) {
          setSummarizeProgress({ current: i + 1, total: chunks.length, combining: false });
          const response = await fetch('/api/chat', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              messages: [
                {
                  role: 'user',
                  content: `Summarize part ${i + 1} of the document:\n\n${chunks[i]}`
                }
              ],
              selectedModel: 'meta-llama/llama-4-scout-17b-16e-instruct'
            })
          });
          const data = await response.json();
          if (!response.ok) throw new Error(data.error || `Failed to summarize part ${i + 1}.`);
          chunkSummaries.push(data.message);
        }

        // Combine
        setSummarizeProgress({ current: chunks.length, total: chunks.length, combining: true });
        const combineResponse = await fetch('/api/chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            messages: [
              {
                role: 'user',
                content: `Please merge and write a cohesive, structured final summary of the document based on these section summaries. Use clear headings and bullet points:\n\n${chunkSummaries.join('\n\n')}`
              }
            ],
            selectedModel: 'meta-llama/llama-4-scout-17b-16e-instruct'
          })
        });
        const combineData = await combineResponse.json();
        if (!combineResponse.ok) throw new Error(combineData.error || 'Failed to generate final summary.');
        finalSummary = combineData.message;
      }

      setSummary(finalSummary);
      setPhase('done');
    } catch (err) {
      console.error(err);
      setError('Failed to summarize: ' + (err?.message || 'unknown error'));
      setPhase('error');
    }
  };

  const resetTool = () => {
    setFile(null);
    setSummary('');
    setError(null);
    setPhase('idle');
    setExtractProgress({ current: 0, total: 0 });
    setSummarizeProgress({ current: 0, total: 0, combining: false });
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {}
  };

  return (
    <div className="tool-page">
      <Link href="/tools/pdf" className="tool-page-back">← Back to PDF Toolkit</Link>
      <div className="tool-page-header">
        <h1>🤖 Summarize PDF</h1>
        <p>Instantly extract and generate structured summaries using Llama AI.</p>
      </div>

      <div
        className="result-container"
        style={{ padding: '20px', background: 'var(--pixel-bg-card)', border: '3px solid var(--pixel-border)' }}
      >
        {error && <div className="error-message" style={{ marginBottom: 16 }}>⚠️ {error}</div>}

        {/* ─── Upload ─── */}
        {phase === 'idle' && (
          <div className="upload-zone" onClick={() => fileInputRef.current?.click()}>
            <div className="upload-zone-icon">🤖</div>
            <div className="upload-zone-text">Click or drag a PDF here to summarize</div>
            <div className="upload-zone-hint">Powered securely by Llama AI</div>
            <input
              type="file" ref={fileInputRef} onChange={handleFileChange}
              accept="application/pdf" style={{ display: 'none' }}
            />
          </div>
        )}

        {/* ─── Extracting progress ─── */}
        {phase === 'extracting' && (
          <div style={{ textAlign: 'center', padding: '50px 20px' }}>
            <div style={{ fontSize: '2.5rem', marginBottom: 18 }}>📖</div>
            <div style={{ fontFamily: 'var(--font-pixel)', color: 'var(--pixel-cyan)', fontSize: '0.85rem', marginBottom: 16 }}>
              READING PAGE {extractProgress.current} / {extractProgress.total}
            </div>
            <div style={{
              width: '60%', maxWidth: 500, margin: '0 auto',
              height: 14, background: '#1a1a1a',
              border: '2px solid var(--pixel-border)', overflow: 'hidden',
            }}>
              <div style={{
                width: `${extractProgress.total ? (extractProgress.current / extractProgress.total) * 100 : 0}%`,
                height: '100%',
                background: 'linear-gradient(90deg, var(--pixel-green) 0%, var(--pixel-cyan) 100%)',
                transition: 'width 0.2s ease',
              }} />
            </div>
          </div>
        )}

        {/* ─── Summarizing progress ─── */}
        {phase === 'summarizing' && (
          <div style={{ textAlign: 'center', padding: '50px 20px' }}>
            <div className="spinner" style={{ width: 60, height: 60, borderWidth: 6, borderColor: 'var(--pixel-green)', borderTopColor: 'transparent', margin: '0 auto' }}></div>
            <h3 style={{ marginTop: '24px', fontFamily: 'var(--font-pixel)', color: 'var(--pixel-green)', textShadow: '2px 2px 0 #000' }}>
              {summarizeProgress.combining 
                ? 'COMBINING SECTION SUMMARIES...' 
                : `LLAMA AI IS SUMMARIZING (PART ${summarizeProgress.current}/${summarizeProgress.total})...`}
            </h3>
          </div>
        )}

        {/* ─── Results page ─── */}
        {(phase === 'done' || phase === 'error') && file && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
            {/* File info */}
            <div style={{
              display: 'flex', alignItems: 'center', gap: 14,
              padding: '10px 14px', background: '#2d1b4e',
              border: '2px dashed var(--pixel-cyan)', flexWrap: 'wrap',
            }}>
              <span style={{ fontSize: '1.3rem' }}>📄</span>
              <strong style={{ color: 'var(--pixel-cyan)' }}>{file.name}</strong>
              <span style={{ color: '#aaa', fontSize: '0.85rem' }}>
                · {extractProgress.total} pages
              </span>
              <div style={{ flex: 1 }} />
              <button className="btn btn-ghost" onClick={resetTool}
                style={{ padding: '6px 12px', fontSize: '0.7rem' }}>
                Summarize Another PDF
              </button>
            </div>

            {summary && (
              <div>
                <div style={{
                  display: 'flex', alignItems: 'center', gap: 12,
                  marginBottom: 10, flexWrap: 'wrap',
                }}>
                  <h3 style={{
                    fontFamily: 'var(--font-pixel)', color: 'var(--pixel-cyan)',
                    fontSize: '1rem', textShadow: '2px 2px 0 #000', margin: 0,
                  }}>
                    SUMMARY
                  </h3>
                  <div style={{ flex: 1 }} />
                  <button className="btn btn-ghost" onClick={handleCopy}
                    style={{ padding: '6px 12px', fontSize: '0.7rem' }}>
                    {copied ? '✓ Copied' : '📋 Copy'}
                  </button>
                  <button className="btn btn-ghost"
                    onClick={() => downloadPdf(summary, `summary_${file.name.replace(/\.pdf$/i, '')}.pdf`)}
                    style={{ padding: '6px 12px', fontSize: '0.7rem' }}>
                    ⬇ .pdf
                  </button>
                  <button className="btn btn-ghost"
                    onClick={() => downloadBlob(summary, `summary_${file.name.replace(/\.pdf$/i, '')}.txt`, 'text/plain')}
                    style={{ padding: '6px 12px', fontSize: '0.7rem' }}>
                    ⬇ .txt
                  </button>
                </div>

                <div
                  className="markdown-body"
                  style={{
                    background: '#2d1b4e', padding: '20px 24px',
                    border: '2px solid var(--pixel-border)', color: '#fff',
                    lineHeight: 1.7, maxHeight: '60vh', overflowY: 'auto',
                    fontSize: '0.95rem',
                  }}
                  dangerouslySetInnerHTML={{ __html: summaryHtml }}
                />
              </div>
            )}
          </div>
        )}
      </div>

      <style jsx global>{`
        .markdown-body { color: #fff; }
        .markdown-body h1,
        .markdown-body h2,
        .markdown-body h3,
        .markdown-body h4 {
          font-family: var(--font-pixel);
          color: var(--pixel-yellow);
          margin: 0.8em 0 0.4em;
        }
        .markdown-body ul,
        .markdown-body ol { padding-left: 1.4em; margin: 0.4em 0; }
        .markdown-body li { margin: 0.25em 0; }
        .markdown-body strong { color: var(--pixel-yellow); }
        .markdown-body code {
          background: rgba(0,0,0,0.4); padding: 1px 5px;
          border-radius: 3px; font-size: 0.85em;
        }
        .markdown-body pre {
          background: #0d0d0d; padding: 10px; overflow-x: auto;
          border: 1px solid #333;
        }
        .markdown-body p { margin: 0.5em 0; }
        .markdown-body hr { border-color: #444; }
      `}</style>
    </div>
  );
}
